packages:
  - .
  - docs
overrides:
  # Override ancient version from @html-eslint/eslint-plugin
  '@eslint/plugin-kit': ~0.7.2
  # Svelte Kit has old insecure version
  cookie: ~1.1.1
  # 0.27.7 is too far...
  # 0.27.6 does not exist?
  esbuild: 0.27.5
publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - case-police
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  canvas: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - tweakpane-plugin-color-plus@0.5.0
