// Figures out prop data from src components
// and writes out a json and / or markdown file with the prop info in the frontmatter for each

import fs from 'node:fs/promises'
import path from 'node:path'
import * as yaml from 'yaml'
import type { ComponentDynamicPropTest } from './component-info'
import {
	format,
	getExportedComponents,
	getGithubUrlForSourceFile,
	getLastUpdatedDate,
} from './ast-tools'
import { getComponentInfo } from './component-info'

async function generateComponentData(
	componentName: string,
	componentPath: string,
	destination: string,
	outputFormat: 'json' | 'mdx', // Must match file extension
	testProps?: ComponentDynamicPropTest[],
): Promise<boolean> {
	const expandedPath = componentPath.replace('$lib', './src/lib')

	const componentInfo = await getComponentInfo(expandedPath, testProps)

	if (componentInfo) {
		// Overwrites existing, creates intermediate directories
		const resolvedPath = path.resolve(`${destination}/${componentName}.${outputFormat}`)
		await fs.mkdir(path.dirname(resolvedPath), { recursive: true })

		let content: string
		switch (outputFormat) {
			case 'json': {
				content = await format(JSON.stringify(componentInfo, undefined, 2), 'json')
				break
			}

			case 'mdx': {
				{
					// Add some extra metadata for Astro
					// The shape of this object needs to be coordinated with the Astro
					// frontmatter schema definitions in docs/src/content/config.ts
					const frontmatter = {
						componentData: componentInfo,
						editUrl: false,
						lastUpdated: (await getLastUpdatedDate(expandedPath)) ?? false,
						note: `Generated by generate-documentation-data.ts from JSDoc information in "${expandedPath}" at ${new Date().toISOString()}. Do not edit directly.`,
						sourceUrl: await getGithubUrlForSourceFile(expandedPath),
						title: componentName,
					}

					content = `---\n${yaml.stringify(frontmatter, {
						toStringDefaults: {
							// DefaultStringType: 'QUOTE_DOUBLE',
							lineWidth: 0,
						},
					})}---\n`

					// Embed example component so we don't have to load it dynamically so that it can prerender to avoid cls
					content += `\nimport Example from '../../../../examples/components/${componentName}Example.svelte';\n`
					content += `\n<Example client:load />\n`
				}

				break
			}
		}

		await fs.writeFile(resolvedPath, content)

		return true
	}

	return false
}

// Main
const components = getExportedComponents('./src/lib/index.ts')
const destination = './docs/src/content/docs/docs/components'
const extension = 'mdx'

console.log(`Generating documentation data for ${components.length} components...`)

try {
	await fs.access(destination)
	console.log(`Removing existing component documentation data at "${destination}"...`)
	await fs.rm(destination, { recursive: true })
} catch {
	// Directory doesn't exist, nothing to remove
}

const results = await Promise.all(
	components.map(async ({ name, path: componentPath }) => {
		//  TODO break out and pass in this config...
		// Pass custom dynamic prop test cases to certain components
		let testProps: ComponentDynamicPropTest[] | undefined

		if (name === 'Pane') {
			testProps = [
				{
					condition: {
						position: 'draggable',
					},
					description: '`position="draggable"`',
				},
				{
					condition: {
						position: 'inline',
					},
					description: '`position="inline"`',
				},
				{
					condition: {
						position: 'fixed',
					},
					description: '`position="fixed"`',
				},
			]
		}

		if (name === 'Monitor') {
			testProps = [
				{
					condition: {
						value: 1,
					},
					description: '`value` is of type `number`',
				},
				{
					condition: {
						value: false,
					},
					description: '`value` is of type `boolean`',
				},
				{
					condition: {
						value: 'string',
					},
					description: '`value` is of type `string`',
				},
			]
		}

		if (name === 'Point') {
			testProps = [
				{
					condition: {
						value: '{[0, 0]}',
					},
					description: '`value` is 2D',
				},
				{
					condition: {
						value: '{[0, 0, 0]}',
					},
					description: '`value` is 3D',
				},
				{
					condition: {
						value: '{[0, 0, 0, 0]}',
					},
					description: '`value` is 4D',
				},
			]
		}

		const success = await generateComponentData(
			name,
			componentPath,
			destination,
			extension,
			testProps,
		)

		if (!success) {
			console.warn(`Issue generating component data for "${name}.svelte"`)
		}

		return success
	}),
)

const totalComponentsGenerated = results.filter(Boolean).length

console.log(
	`Done. Created ${totalComponentsGenerated} component documentation ${extension} files in "${destination}" .`,
)
