name: Set GitHub Metadata
on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Set GitHub Metadata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Sync Package info to GitHub
        uses: kitschpatrol/github-action-repo-sync@v5
        with:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
